### ISSUE TITLE
Peer-Peer code review

### ISSUE THREAD

**Issue by kelomo2502** [edubew/To-do-list#4]
** Well done Winnie;
you have done a very good job with this project .

> Your code looks very well organized and professional

> I think you could look into the color contrast of your UI and see if you could make it a bit brighter

> You have done an amazing job overall
Well-done once again and happy coding!!

**Comment by MicroverseNelson** [comment]
##GOOD JOB
Great job completing your project, 
- you used the classes well
- - you showed good understanding of webpack
## Improvements
- you can use more Es6 code especially arrow functions.
